### ISSUE TITLE
Add U256 -> decimal string conversion

### ISSUE THREAD

**Issue by adamsoffer** [graphprotocol/graph-ts#10]
Since one must set `id` as a string, there is currently no way to use `U256` types as an `id` (unless you turn it into a hex string). Adding a U256 -> decimal string conversion will allow developers to use a number as an id.

**Comment by Jannis** [comment]
This will be resolved via #14 and https://github.com/graphprotocol/graph-node/pull/541 to be merged as well: `someBigInt.toString()` will then return a decimal string.
