### ISSUE TITLE
Document the public interface

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-ts#11]
Right now we're almost completely lacking documentation, we even lost some of the nice docs we [used to have](https://github.com/graphprotocol/graph-cli/blob/f46a0f15098e0cbed0f894e18ffaee1b1c600a8f/index.d.ts). We should have some docs for each public method, especially the more confusing ones such as toHex and toString.

**Comment by Jannis** [comment]
We now have documentation on https://thegraph.com/docs/assemblyscript-api.
