### ISSUE TITLE
Broken tsconfig path

### ISSUE THREAD

**Issue by dapplion** [graphprotocol/graph-ts#113]
The path included in this repo's tsconfig does not appear to exist
https://github.com/graphprotocol/graph-ts/blob/24833299299a025bcda62a7d3948844902dd6e4a/tsconfig.json#L2

The actual version of assemblyscript is this commit

https://github.com/graphprotocol/graph-ts/blob/24833299299a025bcda62a7d3948844902dd6e4a/package.json#L9

which does not contain the path included above
[assemblyscript/tsconfig.assembly.json # 36040d5b5312f19a025782b5e36663823494c2f3](https://github.com/AssemblyScript/assemblyscript/blob/36040d5b5312f19a025782b5e36663823494c2f3/tsconfig.assembly.json) - **404**

See directory of commit [assemblyscript#36040d5b5312f19a025782b5e36663823494c2f3](https://github.com/AssemblyScript/assemblyscript/tree/36040d5b5312f19a025782b5e36663823494c2f3)

---

This prevents running Typescript code in a repo using graph such as https://github.com/aragon/dao-subgraph
```bash
lion:dao-subgraph$ ./node_modules/.bin/ts-node

dao-subgraph/node_modules/ts-node/src/index.ts:423
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS5058: The specified path does not exist: 'dao-subgraph/node_modules/@graphprotocol/graph-ts/node_modules/assemblyscript/tsconfig.assembly.json'.

    at createTSError (dao-subgraph/node_modules/ts-node/src/index.ts:423:12)
    at reportTSError (dao-subgraph/node_modules/ts-node/src/index.ts:427:19)
    at create (dao-subgraph/node_modules/ts-node/src/index.ts:438:36)
    at Object.register (dao-subgraph/node_modules/ts-node/src/index.ts:336:19)
    at main (dao-subgraph/node_modules/ts-node/src/bin.ts:162:19)
    at Object.<anonymous> (dao-subgraph/node_modules/ts-node/src/bin.ts:513:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

**Comment by dapplion** [comment]
Same issue can be recreated with [graphprotocol/uniswap-subgraph](https://github.com/graphprotocol/uniswap-subgraph)

```bash
git clone https://github.com/graphprotocol/uniswap-subgraph.git
cd uniswap-subgraph/
yarn
yarn codegen
ts-node
```

**Comment by j-mars** [comment]
Bump

**Comment by EzeScigo** [comment]
Any solution to this? I think I might having a related issue with yarn installing assemblyscript dependencies.

Thank you

`$ yarn install
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find match for "36040d5b5312f19a025782b5e36663823494c2f3" in "refs/heads/air,refs/heads/asc-encoding,refs/heads/asc-version-dts,refs/heads/asm-div,refs/heads/aspublish,refs/heads/backport-minor,refs/heads/binary-refactor,refs/heads/binaryen-reftypes,refs/heads/crashhandler,refs/heads/eqeqeq,refs/heads/esm-loader,refs/heads/externref-bind,refs/heads/fix-asinit-default-test,refs/heads/fix-asmjs,refs/heads/fix-binary-util,refs/heads/fix-browser-asc,refs/heads/fix-functionArg,refs/heads/fix-getRandomValues,refs/heads/fix-minimal,refs/heads/fix-newArray,refs/heads/fix-publish,refs/heads/fix-runpasses-oneoff,refs/heads/fix-sourcemap-column,refs/heads/fix-startorder,refs/heads/fix-staticarray-id,refs/heads/fix-staticmem,refs/heads/inc,refs/heads/issue-1186,refs/heads/issue-1374,refs/heads/issue-1379,refs/heads/issue-1386,refs/heads/issue-1398,refs/heads/issue-1400,refs/heads/issue-1404,refs/heads/issue-1409,refs/heads/issue-1483,refs/heads/issue-1536,refs/heads/issue-1547,refs/heads/issue-1585,refs/heads/issue-1599,refs/heads/issue-1622,refs/heads/issue-1637,refs/heads/issue-1644,refs/heads/issue-1652,refs/heads/issue-1654,refs/heads/issue-1673,refs/heads/issue-1675,refs/heads/issue-1677,refs/heads/issue-1711,refs/heads/issue-1714,refs/heads/issue-1746,refs/heads/issue-1751,refs/heads/issue-1753,refs/heads/issue-1785,refs/heads/issue-1795,refs/heads/itcms-coldstart,refs/heads/loader-esm,refs/heads/master,refs/heads/memoryData,refs/heads/nontrapping-f2i,refs/heads/notempfree,refs/heads/nullish,refs/heads/optimize-shadowstack,refs/heads/optimize-shorthands,refs/heads/package-exports,refs/heads/release,refs/heads/relocatable,refs/heads/rtrace-constants,refs/heads/rtrace-esm,refs/heads/rtrace-shadow,refs/heads/scopeanalyzer,refs/heads/sdk-transform,refs/heads/simd-misc,refs/heads/simd-types,refs/heads/size-tostring,refs/heads/stw,refs/heads/stw-backport,refs/heads/stw-mathdiff,refs/heads/template-literal-parsing,refs/heads/threadsafe,refs/heads/throw-try-catch,refs/heads/tracing-prep,refs/heads/trim-data-segments,refs/heads/try-catch,refs/heads/typedefault,refs/heads/unify-ensure-ctor,refs/heads/update-binaryen,refs/heads/update-deps,refs/heads/update-rtrace-defs,refs/heads/update-simd,refs/heads/zeroseventeen-comments,refs/tags/v0.10.0,refs/tags/v0.10.0-nightly.20200517,refs/tags/v0.10.0-nightly.20200526,refs/tags/v0.10.0-nightly.20200528,refs/tags/v0.10.0-nightly.20200529,refs/tags/v0.10.0-nightly.20200530,refs/tags/v0.10.0-nightly.20200610,refs/tags/v0.10.0-nightly.20200611,refs/tags/v0.10.1,refs/tags/v0.10.2,refs/tags/v0.11.0,refs/tags/v0.12.0,refs/tags/v0.12.1,refs/tags/v0.12.2,refs/tags/v0.12.3,refs/tags/v0.12.4,refs/tags/v0.12.5,refs/tags/v0.12.6,refs/tags/v0.13.0,refs/tags/v0.13.1,refs/tags/v0.13.2,refs/tags/v0.13.3,refs/tags/v0.13.4,refs/tags/v0.13.5,refs/tags/v0.13.6,refs/tags/v0.13.7,refs/tags/v0.13.8,refs/tags/v0.14.0,refs/tags/v0.14.1,refs/tags/v0.14.10,refs/tags/v0.14.11,refs/tags/v0.14.12,refs/tags/v0.14.13,refs/tags/v0.14.2,refs/tags/v0.14.3,refs/tags/v0.14.4,refs/tags/v0.14.5,refs/tags/v0.14.6,refs/tags/v0.14.7,refs/tags/v0.14.8,refs/tags/v0.14.9,refs/tags/v0.15.0,refs/tags/v0.15.1,refs/tags/v0.15.2,refs/tags/v0.16.0,refs/tags/v0.16.1,refs/tags/v0.17.0,refs/tags/v0.17.1,refs/tags/v0.17.10,refs/tags/v0.17.11,refs/tags/v0.17.12,refs/tags/v0.17.13,refs/tags/v0.17.14,refs/tags/v0.17.2,refs/tags/v0.17.3,refs/tags/v0.17.4,refs/tags/v0.17.5,refs/tags/v0.17.6,refs/tags/v0.17.7,refs/tags/v0.17.8,refs/tags/v0.17.9,refs/tags/v0.18.0,refs/tags/v0.18.1,refs/tags/v0.18.10,refs/tags/v0.18.11,refs/tags/v0.18.12,refs/tags/v0.18.13,refs/tags/v0.18.14,refs/tags/v0.18.15,refs/tags/v0.18.16,refs/tags/v0.18.17,refs/tags/v0.18.18,refs/tags/v0.18.19,refs/tags/v0.18.2,refs/tags/v0.18.20,refs/tags/v0.18.21,refs/tags/v0.18.22,refs/tags/v0.18.23,refs/tags/v0.18.24,refs/tags/v0.18.25,refs/tags/v0.18.26,refs/tags/v0.18.27,refs/tags/v0.18.28,refs/tags/v0.18.29,refs/tags/v0.18.3,refs/tags/v0.18.30,refs/tags/v0.18.31,refs/tags/v0.18.4,refs/tags/v0.18.5,refs/tags/v0.18.6,refs/tags/v0.18.7,refs/tags/v0.18.8,refs/tags/v0.18.9,refs/tags/v0.6,refs/tags/v0.8.0,refs/tags/v0.8.0-nightly.20191109,refs/tags/v0.8.0-nightly.20191110,refs/tags/v0.8.0-nightly.20191114,refs/tags/v0.8.0-nightly.20191115,refs/tags/v0.8.0-nightly.20191117,refs/tags/v0.8.1,refs/tags/v0.8.1-nightly.20191119,refs/tags/v0.8.1-nightly.20191121,refs/tags/v0.8.1-nightly.20191124,refs/tags/v0.8.1-nightly.20191130,refs/tags/v0.8.1-nightly.20191201,refs/tags/v0.8.1-nightly.20191205,refs/tags/v0.8.1-nightly.20191208,refs/tags/v0.8.1-nightly.20191209,refs/tags/v0.8.1-nightly.20191214,refs/tags/v0.8.1-nightly.20191218,refs/tags/v0.8.1-nightly.20191219,refs/tags/v0.8.1-nightly.20191220,refs/tags/v0.8.1-nightly.20191221,refs/tags/v0.8.1-nightly.20191228,refs/tags/v0.8.1-nightly.20191229,refs/tags/v0.8.1-nightly.20200101,refs/tags/v0.8.1-nightly.20200102,refs/tags/v0.8.1-nightly.20200110,refs/tags/v0.8.1-nightly.20200111,refs/tags/v0.8.1-nightly.20200112,refs/tags/v0.8.1-nightly.20200114,refs/tags/v0.8.1-nightly.20200119,refs/tags/v0.8.1-nightly.20200120,refs/tags/v0.8.1-nightly.20200123,refs/tags/v0.8.1-nightly.20200125,refs/tags/v0.9.0,refs/tags/v0.9.0-nightly.20200127,refs/tags/v0.9.0-nightly.20200129,refs/tags/v0.9.1,refs/tags/v0.9.1-nightly.20200131,refs/tags/v0.9.1-nightly.20200209,refs/tags/v0.9.1-nightly.20200210,refs/tags/v0.9.1-nightly.20200212,refs/tags/v0.9.2,refs/tags/v0.9.2-nightly.20200227,refs/tags/v0.9.2-nightly.20200228,refs/tags/v0.9.2-nightly.20200304,refs/tags/v0.9.2-nightly.20200310,refs/tags/v0.9.3,refs/tags/v0.9.4,refs/tags/v0.9.4-nightly.20200314,refs/tags/v0.9.4-nightly.20200315,refs/tags/v0.9.4-nightly.20200316,refs/tags/v0.9.4-nightly.20200325,refs/tags/v0.9.4-nightly.20200329,refs/tags/v0.9.4-nightly.20200401,refs/tags/v0.9.4-nightly.20200402,refs/tags/v0.9.4-nightly.20200411,refs/tags/v0.9.4-nightly.20200413,refs/tags/v0.9.4-nightly.20200414,refs/tags/v0.9.4-nightly.20200416,refs/tags/v0.9.4-nightly.20200421,refs/tags/v0.9.4-nightly.20200422,refs/tags/v0.9.4-nightly.20200423,refs/tags/v0.9.4-nightly.20200427,refs/tags/v0.9.4-nightly.20200428,refs/tags/v0.9.4-nightly.20200429,refs/tags/v0.9.4-nightly.20200430,refs/tags/v0.9.4-nightly.20200506,refs/tags/v0.9.4-nightly.20200509,refs/tags/v0.9.4-nightly.20200510,refs/tags/v0.9.4-nightly.20200514" for "https://github.com/AssemblyScript/assemblyscript".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Comment by piavgh** [comment]
I met this issue if I run `yarn` to install dependencies

But `npm install` works properly, I don't know why

**Comment by schmidsi** [comment]
This is linked to the failing build here: https://travis-ci.com/github/graphprotocol/graph-cli/jobs/485964066#L346

**Comment by schmidsi** [comment]
I think we were able to fix this by releasing a new version of the `graph-cli`. Can you please try to install it again like: `yarn global add @graphprotocol/graph-cli@0.20.1`

**Comment by dan13ram** [comment]
Hey @schmidsi,
This issue is still not fixed entirely. 
The package.json for `@graphprotocol/graph-ts@0.20.0` still contains the version of assembly script that is failing.
https://github.com/graphprotocol/graph-ts/blob/c18868afe9666a2283cbaa54692ea78608e8a50d/package.json#L8

And this makes `yarn` commands fail.

**Comment by dan13ram** [comment]
I was able to fix this for now by adding this to my package.json
```
  "resolutions": {
    "assemblyscript": "git+https://github.com/AssemblyScript/assemblyscript.git#v0.6"
  }
```

**Comment by schmidsi** [comment]
Yes, good catch. Thanks for the update. We need to update `graph-ts` also.

**Comment by ydaydayup** [comment]
@schmidsi 感谢您的答案，谢谢

**Comment by schmidsi** [comment]
We just released [@graphprotocol/graph-ts@0.20.1](https://www.npmjs.com/package/@graphprotocol/graph-ts/v/0.20.1), depending on an old but hopefully stable AssemblyScript version.

If you still have problems, make sure to have the latest graph-cli globally installed: `yarn global add @graphprotocol/graph-cli@0.20.1`.

If you created a subgraph-repo recently, make sure to update the dependencies:
```json
  "devDependencies": {
    "@graphprotocol/graph-cli": "^0.20.1",
    "@graphprotocol/graph-ts": "^0.20.1"
  },
```

If you were affected by this bug somehow, please verify that we fixed it with these changes. If someone still has issues, please reopen this ticket.

**Comment by porobov** [comment]
Got into a similar issue  when running:
**graph init --from-example user/test**

Ubuntu 18.04.5 LTS
Node v10.20.1

```
✔ Product for which to initialize · subgraph-studio
✔ Subgraph slug · user/test
✔ Directory to create the subgraph in · test
———
✔ Cloning example subgraph
✔ Update subgraph name and commands in package.json
✔ Initialize subgraph repository
✖ Failed to install dependencies: Command failed: yarn
error Couldn't find match for "36040d5b5312f19a025782b5e36663823494c2f3" in "refs/heads/air,refs/heads/encode16-fast,refs/heads/eqeqeq,refs/heads/externref-bind,refs/heads/main,refs/heads/memoryData,refs/heads/notempfree,refs/heads/nullish,refs/heads/portable-once,refs/heads/release,refs/heads/relocatable,refs/heads/scopeanalyzer,refs/heads/static-logical,refs/heads/threadsafe,refs/heads/trim-data-segments,refs/tags/v0.10.0,refs/tags/v0.10.0-nightly.20200517,refs/tags/v0.10.0-nightly.20200526,refs/tags/v0.10.0-nightly.20200528,refs/tags/v0.10.0-nightly.20200529,refs/tags/v0.10.0-nightly.20200530,refs/tags/v0.10.0-nightly.20200610,refs/tags/v0.10.0-nightly.20200611,refs/tags/v0.10.1,refs/tags/v0.10.2,refs/tags/v0.11.0,refs/tags/v0.12.0,refs/tags/v0.12.1,refs/tags/v0.12.2,refs/tags/v0.12.3,refs/tags/v0.12.4,refs/tags/v0.12.5,refs/tags/v0.12.6,refs/tags/v0.13.0,refs/tags/v0.13.1,refs/tags/v0.13.2,refs/tags/v0.13.3,refs/tags/v0.13.4,refs/tags/v0.13.5,refs/tags/v0.13.6,refs/tags/v0.13.7,refs/tags/v0.13.8,refs/tags/v0.14.0,refs/tags/v0.14.1,refs/tags/v0.14.10,refs/tags/v0.14.11,refs/tags/v0.14.12,refs/tags/v0.14.13,refs/tags/v0.14.2,refs/tags/v0.14.3,refs/tags/v0.14.4,refs/tags/v0.14.5,refs/tags/v0.14.6,refs/tags/v0.14.7,refs/tags/v0.14.8,refs/tags/v0.14.9,refs/tags/v0.15.0,refs/tags/v0.15.1,refs/tags/v0.15.2,refs/tags/v0.16.0,refs/tags/v0.16.1,refs/tags/v0.17.0,refs/tags/v0.17.1,refs/tags/v0.17.10,refs/tags/v0.17.11,refs/tags/v0.17.12,refs/tags/v0.17.13,refs/tags/v0.17.14,refs/tags/v0.17.2,refs/tags/v0.17.3,refs/tags/v0.17.4,refs/tags/v0.17.5,refs/tags/v0.17.6,refs/tags/v0.17.7,refs/tags/v0.17.8,refs/tags/v0.17.9,refs/tags/v0.18.0,refs/tags/v0.18.1,refs/tags/v0.18.10,refs/tags/v0.18.11,refs/tags/v0.18.12,refs/tags/v0.18.13,refs/tags/v0.18.14,refs/tags/v0.18.15,refs/tags/v0.18.16,refs/tags/v0.18.17,refs/tags/v0.18.18,refs/tags/v0.18.19,refs/tags/v0.18.2,refs/tags/v0.18.20,refs/tags/v0.18.21,refs/tags/v0.18.22,refs/tags/v0.18.23,refs/tags/v0.18.24,refs/tags/v0.18.25,refs/tags/v0.18.26,refs/tags/v0.18.27,refs/tags/v0.18.28,refs/tags/v0.18.29,refs/tags/v0.18.3,refs/tags/v0.18.30,refs/tags/v0.18.31,refs/tags/v0.18.32,refs/tags/v0.18.4,refs/tags/v0.18.5,refs/tags/v0.18.6,refs/tags/v0.18.7,refs/tags/v0.18.8,refs/tags/v0.18.9,refs/tags/v0.19.0,refs/tags/v0.19.1,refs/tags/v0.19.2,refs/tags/v0.19.3,refs/tags/v0.19.4,refs/tags/v0.19.5,refs/tags/v0.19.6,refs/tags/v0.19.7,refs/tags/v0.6,refs/tags/v0.8.0,refs/tags/v0.8.0-nightly.20191109,refs/tags/v0.8.0-nightly.20191110,refs/tags/v0.8.0-nightly.20191114,refs/tags/v0.8.0-nightly.20191115,refs/tags/v0.8.0-nightly.20191117,refs/tags/v0.8.1,refs/tags/v0.8.1-nightly.20191119,refs/tags/v0.8.1-nightly.20191121,refs/tags/v0.8.1-nightly.20191124,refs/tags/v0.8.1-nightly.20191130,refs/tags/v0.8.1-nightly.20191201,refs/tags/v0.8.1-nightly.20191205,refs/tags/v0.8.1-nightly.20191208,refs/tags/v0.8.1-nightly.20191209,refs/tags/v0.8.1-nightly.20191214,refs/tags/v0.8.1-nightly.20191218,refs/tags/v0.8.1-nightly.20191219,refs/tags/v0.8.1-nightly.20191220,refs/tags/v0.8.1-nightly.20191221,refs/tags/v0.8.1-nightly.20191228,refs/tags/v0.8.1-nightly.20191229,refs/tags/v0.8.1-nightly.20200101,refs/tags/v0.8.1-nightly.20200102,refs/tags/v0.8.1-nightly.20200110,refs/tags/v0.8.1-nightly.20200111,refs/tags/v0.8.1-nightly.20200112,refs/tags/v0.8.1-nightly.20200114,refs/tags/v0.8.1-nightly.20200119,refs/tags/v0.8.1-nightly.20200120,refs/tags/v0.8.1-nightly.20200123,refs/tags/v0.8.1-nightly.20200125,refs/tags/v0.9.0,refs/tags/v0.9.0-nightly.20200127,refs/tags/v0.9.0-nightly.20200129,refs/tags/v0.9.1,refs/tags/v0.9.1-nightly.20200131,refs/tags/v0.9.1-nightly.20200209,refs/tags/v0.9.1-nightly.20200210,refs/tags/v0.9.1-nightly.20200212,refs/tags/v0.9.2,refs/tags/v0.9.2-nightly.20200227,refs/tags/v0.9.2-nightly.20200228,refs/tags/v0.9.2-nightly.20200304,refs/tags/v0.9.2-nightly.20200310,refs/tags/v0.9.3,refs/tags/v0.9.4,refs/tags/v0.9.4-nightly.20200314,refs/tags/v0.9.4-nightly.20200315,refs/tags/v0.9.4-nightly.20200316,refs/tags/v0.9.4-nightly.20200325,refs/tags/v0.9.4-nightly.20200329,refs/tags/v0.9.4-nightly.20200401,refs/tags/v0.9.4-nightly.20200402,refs/tags/v0.9.4-nightly.20200411,refs/tags/v0.9.4-nightly.20200413,refs/tags/v0.9.4-nightly.20200414,refs/tags/v0.9.4-nightly.20200416,refs/tags/v0.9.4-nightly.20200421,refs/tags/v0.9.4-nightly.20200422,refs/tags/v0.9.4-nightly.20200423,refs/tags/v0.9.4-nightly.20200427,refs/tags/v0.9.4-nightly.20200428,refs/tags/v0.9.4-nightly.20200429,refs/tags/v0.9.4-nightly.20200430,refs/tags/v0.9.4-nightly.20200506,refs/tags/v0.9.4-nightly.20200509,refs/tags/v0.9.4-nightly.20200510,refs/tags/v0.9.4-nightly.20200514" for "https://github.com/AssemblyScript/assemblyscript".

/home/user/.nvm/versions/node/v10.20.1/lib/node_modules/@graphprotocol/graph-cli/node_modules/binaryen/index.js:7
if(n){p=__dirname+"/";var ea,fa;a.read=function(c,e){var b=q(c);b||(ea||(ea=require("fs")),fa||(fa=require("path")),c=fa.normalize(c),b=ea.readFileSync(c));return e?b:b.toString()};a.readBinary=function(c){c=a.read(c,!0);c.buffer||(c=new Uint8Array(c));assert(c.buffer);return c};1<process.argv.length&&(a.thisProgram=process.argv[1].replace(/\\/g,"/"));a.arguments=process.argv.slice(2);process.on("uncaughtException",function(c){if(!(c instanceof ha))throw c;});process.on("unhandledRejection",u);a.quit=
                                                                                                                                                                                                                   

Error: Command failed: yarn
error Couldn't find match for "36040d5b5312f19a025782b5e36663823494c2f3" in "refs/heads/air,refs/heads/encode16-fast,refs/heads/eqeqeq,refs/heads/externref-bind,refs/heads/main,refs/heads/memoryData,refs/heads/notempfree,refs/heads/nullish,refs/heads/portable-once,refs/heads/release,refs/heads/relocatable,refs/heads/scopeanalyzer,refs/heads/static-logical,refs/heads/threadsafe,refs/heads/trim-data-segments,refs/tags/v0.10.0,refs/tags/v0.10.0-nightly.20200517,refs/tags/v0.10.0-nightly.20200526,refs/tags/v0.10.0-nightly.20200528,refs/tags/v0.10.0-nightly.20200529,refs/tags/v0.10.0-nightly.20200530,refs/tags/v0.10.0-nightly.20200610,refs/tags/v0.10.0-nightly.20200611,refs/tags/v0.10.1,refs/tags/v0.10.2,refs/tags/v0.11.0,refs/tags/v0.12.0,refs/tags/v0.12.1,refs/tags/v0.12.2,refs/tags/v0.12.3,refs/tags/v0.12.4,refs/tags/v0.12.5,refs/tags/v0.12.6,refs/tags/v0.13.0,refs/tags/v0.13.1,refs/tags/v0.13.2,refs/tags/v0.13.3,refs/tags/v0.13.4,refs/tags/v0.13.5,refs/tags/v0.13.6,refs/tags/v0.13.7,refs/tags/v0.13.8,refs/tags/v0.14.0,refs/tags/v0.14.1,refs/tags/v0.14.10,refs/tags/v0.14.11,refs/tags/v0.14.12,refs/tags/v0.14.13,refs/tags/v0.14.2,refs/tags/v0.14.3,refs/tags/v0.14.4,refs/tags/v0.14.5,refs/tags/v0.14.6,refs/tags/v0.14.7,refs/tags/v0.14.8,refs/tags/v0.14.9,refs/tags/v0.15.0,refs/tags/v0.15.1,refs/tags/v0.15.2,refs/tags/v0.16.0,refs/tags/v0.16.1,refs/tags/v0.17.0,refs/tags/v0.17.1,refs/tags/v0.17.10,refs/tags/v0.17.11,refs/tags/v0.17.12,refs/tags/v0.17.13,refs/tags/v0.17.14,refs/tags/v0.17.2,refs/tags/v0.17.3,refs/tags/v0.17.4,refs/tags/v0.17.5,refs/tags/v0.17.6,refs/tags/v0.17.7,refs/tags/v0.17.8,refs/tags/v0.17.9,refs/tags/v0.18.0,refs/tags/v0.18.1,refs/tags/v0.18.10,refs/tags/v0.18.11,refs/tags/v0.18.12,refs/tags/v0.18.13,refs/tags/v0.18.14,refs/tags/v0.18.15,refs/tags/v0.18.16,refs/tags/v0.18.17,refs/tags/v0.18.18,refs/tags/v0.18.19,refs/tags/v0.18.2,refs/tags/v0.18.20,refs/tags/v0.18.21,refs/tags/v0.18.22,refs/tags/v0.18.23,refs/tags/v0.18.24,refs/tags/v0.18.25,refs/tags/v0.18.26,refs/tags/v0.18.27,refs/tags/v0.18.28,refs/tags/v0.18.29,refs/tags/v0.18.3,refs/tags/v0.18.30,refs/tags/v0.18.31,refs/tags/v0.18.32,refs/tags/v0.18.4,refs/tags/v0.18.5,refs/tags/v0.18.6,refs/tags/v0.18.7,refs/tags/v0.18.8,refs/tags/v0.18.9,refs/tags/v0.19.0,refs/tags/v0.19.1,refs/tags/v0.19.2,refs/tags/v0.19.3,refs/tags/v0.19.4,refs/tags/v0.19.5,refs/tags/v0.19.6,refs/tags/v0.19.7,refs/tags/v0.6,refs/tags/v0.8.0,refs/tags/v0.8.0-nightly.20191109,refs/tags/v0.8.0-nightly.20191110,refs/tags/v0.8.0-nightly.20191114,refs/tags/v0.8.0-nightly.20191115,refs/tags/v0.8.0-nightly.20191117,refs/tags/v0.8.1,refs/tags/v0.8.1-nightly.20191119,refs/tags/v0.8.1-nightly.20191121,refs/tags/v0.8.1-nightly.20191124,refs/tags/v0.8.1-nightly.20191130,refs/tags/v0.8.1-nightly.20191201,refs/tags/v0.8.1-nightly.20191205,refs/tags/v0.8.1-nightly.20191208,refs/tags/v0.8.1-nightly.20191209,refs/tags/v0.8.1-nightly.20191214,refs/tags/v0.8.1-nightly.20191218,refs/tags/v0.8.1-nightly.20191219,refs/tags/v0.8.1-nightly.20191220,refs/tags/v0.8.1-nightly.20191221,refs/tags/v0.8.1-nightly.20191228,refs/tags/v0.8.1-nightly.20191229,refs/tags/v0.8.1-nightly.20200101,refs/tags/v0.8.1-nightly.20200102,refs/tags/v0.8.1-nightly.20200110,refs/tags/v0.8.1-nightly.20200111,refs/tags/v0.8.1-nightly.20200112,refs/tags/v0.8.1-nightly.20200114,refs/tags/v0.8.1-nightly.20200119,refs/tags/v0.8.1-nightly.20200120,refs/tags/v0.8.1-nightly.20200123,refs/tags/v0.8.1-nightly.20200125,refs/tags/v0.9.0,refs/tags/v0.9.0-nightly.20200127,refs/tags/v0.9.0-nightly.20200129,refs/tags/v0.9.1,refs/tags/v0.9.1-nightly.20200131,refs/tags/v0.9.1-nightly.20200209,refs/tags/v0.9.1-nightly.20200210,refs/tags/v0.9.1-nightly.20200212,refs/tags/v0.9.2,refs/tags/v0.9.2-nightly.20200227,refs/tags/v0.9.2-nightly.20200228,refs/tags/v0.9.2-nightly.20200304,refs/tags/v0.9.2-nightly.20200310,refs/tags/v0.9.3,refs/tags/v0.9.4,refs/tags/v0.9.4-nightly.20200314,refs/tags/v0.9.4-nightly.20200315,refs/tags/v0.9.4-nightly.20200316,refs/tags/v0.9.4-nightly.20200325,refs/tags/v0.9.4-nightly.20200329,refs/tags/v0.9.4-nightly.20200401,refs/tags/v0.9.4-nightly.20200402,refs/tags/v0.9.4-nightly.20200411,refs/tags/v0.9.4-nightly.20200413,refs/tags/v0.9.4-nightly.20200414,refs/tags/v0.9.4-nightly.20200416,refs/tags/v0.9.4-nightly.20200421,refs/tags/v0.9.4-nightly.20200422,refs/tags/v0.9.4-nightly.20200423,refs/tags/v0.9.4-nightly.20200427,refs/tags/v0.9.4-nightly.20200428,refs/tags/v0.9.4-nightly.20200429,refs/tags/v0.9.4-nightly.20200430,refs/tags/v0.9.4-nightly.20200506,refs/tags/v0.9.4-nightly.20200509,refs/tags/v0.9.4-nightly.20200510,refs/tags/v0.9.4-nightly.20200514" for "https://github.com/AssemblyScript/assemblyscript".

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

```

**Comment by porobov** [comment]
I managed to finish graph initialization by fixing package.json in the generated folder (which is [YOUR GRAPH NAME]) like this - https://github.com/graphprotocol/graph-ts/issues/113#issuecomment-860062633
Then I did `yarn` and proceeded the tutorial from step 4 - https://thegraph.com/docs/developer/quick-start

**Comment by wswarren12** [comment]
Still experiencing this error with npm after running `npm install` even after upgrading dev dependencies to: 

```
  "devDependencies": {
    "@graphprotocol/graph-cli": "^0.20.1",
    "@graphprotocol/graph-ts": "^0.20.1"
  },
```
  
  and my global is also on version 0.20.01. 
  
  adding the resolutions didn't work either.

**Comment by schmidsi** [comment]
@wswarren12, the latest version of graph-cli is v0.25.1. Please follow the upgrade guide here to upgrade your project: https://thegraph.com/docs/en/developer/assemblyscript-migration-guide/. We can not provide support for legacy versions.
