### ISSUE TITLE
Feature Request: HTTP API

### ISSUE THREAD

**Issue by dasconnor** [graphprotocol/graph-ts#142]
It would be great if you guys could add an endpoint for external HTTP requests. I'm currently building a subgraph on an alternate, Ethereum-like chain that lacks some of Ethereum's smart contract deployments and not all data is available on-chain.

**Comment by cauta** [comment]
any news on this? Or can we use external assemblyscript like as-fetch?

**Comment by leoyvens** [comment]
HTTP calls to arbitrary are not deterministic so this is not supported.
