### ISSUE TITLE
Error Calling old contract function

### ISSUE THREAD

**Issue by cauta** [graphprotocol/graph-ts#207]
I'm facing the issue when redeploy the subgraph on goerli tesnet
the error happens when my contract was deployed about a week
it can not retrieve contract function although i can call from etherscan
```
Sep 20 04:11:01.363 ERRO Subgraph instance failed to run: Mapping aborted at ~lib/@graphprotocol/graph-ts/chain/ethereum.ts, line 440, column 7, with message: Call reverted, prob
ably because an `assert` or `require` in the contract failed, consider using `try_getRock` to handle this in the mapping.       wasm backtrace:     0: 0x12f7 - <unknown>!~lib/@gr
aphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#call     1: 0x1af2 - <unknown>!src/handlers/rock/buildRock       2: 0x21f2 - <unknown>!src/handlers/rock/handleTransfer
 in handler `handleTransfer` at block #5513715 (5b2de2e3cd4af065a6add507dcdcb6e44352ae3502121b4a193a634212eadb4d), code: SubgraphSyncingFailure, sgd: 3, subgraph_id: QmW2pmREu68R
q79FHVdxox1LE6DEvGvzmm6ScUp5HwPphj, component: SubgraphInstanceManager
```
The issue seem disappear when i create new contract and redeploy

graph-cli version: 0.21.1 & 0.22.0 both the same issue
graph-node 0.24.0
graph-ts: 0.22.0
apiVersion 0.0.4 & 0.0.5 both the same

this is the error lines:
```
let core = TheRocksCore.bind(Address.fromString(TheRocksCoreAddress));
function buildRock(rockId: BigInt, timestamp: BigInt): Rock {
  let rock = Rock.load(rockId.toString());
  if (!rock) {
    let token = core.getRock(rockId);  //ERROR HERE
    rock = new Rock(rockId.toString());
  }
  return rock;
}
```

this is self hosting subgraph

**Comment by leoyvens** [comment]
Please make sure you are on graph node 0.24.1, not 0.24.0

**Comment by cauta** [comment]
Thanks for your support. Why we need an archive node when calling contract function? My web3 still get the results on fullnode anyway?

**Comment by leoyvens** [comment]
Archive nodes are required for calls against old blocks. Could you confirm what graph-node version you were on when you got this error?

**Comment by cauta** [comment]
my graph-node version is 0.24.0.


> Archive nodes are required for calls against old blocks. Could you confirm what graph-node version you were on when you got this error?

**Comment by cauta** [comment]
Can we make a different approach when calling contract function like web3?
