### ISSUE TITLE
null is not assignable to type

### ISSUE THREAD

**Issue by sirpy** [graphprotocol/graph-ts#214]
using 0.22.3 doesnt happen with 0.20
Even though the generated class field return type is BigInt | null
If you compare the field value to null you get the following error:
```
Compile subgraphERROR TS2322: Type '~lib/@graphprotocol/graph-ts/common/numbers/BigInt | null' is not assignable to type '~lib/@graphprotocol/graph-ts/common/numbers/BigInt'.

  if(entity.count == null)
```

the generated field is:
```
  get count(): BigInt | null {
    let value = this.get("count");
    if (!value || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }
```

**Comment by abhishekwin** [comment]
get count(): BigInt | null {
    let value = this.get("count");
    if (!value || value.kind === ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

**Comment by KholdStare** [comment]
I am getting this as well.

**Comment by maoueh** [comment]
You need to handle the `null` value correctly. If you are already sure the value is non-null but the compiler does not seem to be able to "see" it, you can suffix your usage with `!` which tells the compiler `hey, this is non-null treat it as T and not as T | null`.

If you show the piece of code that fails for you, we can suggest way to avoid the compilation. 

I think the AssemblyScript compiler was updated between 0.20 and 0.22.3 which could be why new errors are being displayed. Closing as it not directly a bug in `graph-ts` as far as I can see, feel free to re-open if I'm mistaken.
