### ISSUE TITLE
BigInt.fromI32() import error

### ISSUE THREAD

**Issue by RongxinZhang** [graphprotocol/graph-ts#239]
**Description:**
I am building a react app that uses the Graph to query for data.
However, I need to have a BigInt as a parameter for the query.

I have the following code to perform type conversions:
```js
  import { BigInt } from "@graphprotocol/graph-ts"
  const NOW = Math.floor(Date.now() / 1000)
  const currentDate = BigInt.fromI32(NOW)
```

However, when I run the app, I get the following error:
`Attempted import error: 'typeConversion' is not exported from './conversion'.`

**OS:**
Ubuntu 20.04.3 LTS

Any advice would be greatly appreciated: @Jannis

**Comment by schmidsi** [comment]
Hey @RongxinZhang, the `graph-ts` naming is unfortunately misleading: To query The Graph from a client, you can just use a standard GraphQL library like [Apollo Client](https://www.apollographql.com/apollo-client). There you have all types properly hinted and enforced from GraphQL. `@graphprotocol/graph-ts` is not meant to be a dependency of your consumer code, it is actually an AssembyScript library that provides utilities and typings for writing subgraphs.

Hint: You can not use `Date` in your subgraphs.

I hope this helps. Feel free to reopen this issue if you still have questions.
