### ISSUE TITLE
Feature Request: Source - Block instead of Address

### ISSUE THREAD

**Issue by Data-Nexus** [graphprotocol/graph-ts#242]
I built a quick subgraph to monitor gas fees and other relevant block information. Currently it's listening to a contract that has interaction in over 90% of blocks, however it'd be ideal for the subgraph to listen to every block.

**Comment by maoueh** [comment]
There is a BlockHandler that can be used for that. The BlockHandler can trigger on each block but you receive a `ethereum.Block` as the input, which is maybe not what you would like.

The `BlockHandler` still requires a source address but this is a bug in the validation that should not be present, so you are good as a workaround to simply set the source to an empty address like `0x0000000000000000000000000000000000000000`.

**Comment by Data-Nexus** [comment]
Thank you. This worked beautifully.
