### ISSUE TITLE
Question: Does 'entities' field actually matter?

### ISSUE THREAD

**Issue by colonelssecretspices** [graphprotocol/graph-ts#243]
Hi, I've realized that all this time I've been using the "entities" field incorrectly. Rather than filling in the entities that will be processed, I have been basically using the same value as the name of the dataSource.

However, I also realized that this doesn't seem to actually have any bearing to the results of the subgraph? Is this so? What impacts does the entities field actually make?

**Comment by leoyvens** [comment]
That field is currently ignored.

**Comment by schmidsi** [comment]
I think this question is answered. So closing this. Feel free to reopen.
