### ISSUE TITLE
ERROR TS2322: Type '~lib/array/Array<~lib/@graphprotocol/graph-ts/common/numbers/Address>' is not assignable to type '~lib/array/Array<~lib/@graphprotocol/graph-ts/common/collections/Bytes>'

### ISSUE THREAD

**Issue by damozhang** [graphprotocol/graph-ts#246]
```
ERROR TS2322: Type '~lib/array/Array<~lib/@graphprotocol/graph-ts/common/numbers/Address>' is not assignable to type '~lib/array/Array<~lib/@graphprotocol/graph-ts/common/collections/Bytes>'

proposal.targets = event.params.targets as Bytes[];
```

the event.params.targets

```
get targets(): Array<Address> {
    return this._event.parameters[2].value.toAddressArray();
}
```

**Comment by r-marques** [comment]
Any update on this? Having the same problem

**Comment by cold-briu** [comment]
A variable typed as Array<Address> Can't store a Array<Bytes> value.
"proposal. targets" expects a Array<Address> but you are passing an Array<Bytes> value. 
You can go to the generated folder and check if the "event.params.targets" definition. 
1. if it's type is an Array<Address> don't try to cast it to Array<Bytes>.
2. if it's type is Array<Bytes> you need to parse it.

**Comment by r-marques** [comment]
Thanks that worked. But I think the code generation is wrongly setting some variable to Bytes[] when thy are actual Addresses[].
I'm not sure but I think this only happens with Arrays

**Comment by cold-briu** [comment]
Can you elaborate more, please?

**Comment by ksvirsky** [comment]
Having the same problem. Need to save value to
```
type Model @entity {
  list: [Bytes!]!
}
```
It worked well until updated to the latest version of the protocol. And now the code:
```
m.list = contract.getAddressList() as Bytes[];
```
returns the error (`Compile subgraphERROR TS2322: Type '~lib/array/Array<~lib/@graphprotocol/graph-ts/common/numbers/Address>' is not assignable to type '~lib/array/Array<~lib/@graphprotocol/graph-ts/common/collections/Bytes>'.`).

The contract code is generated as:
  ```
getAddressList(): Array<Address> {
    let result = super.call(
      "getAddressList",
      "getAddressList():(address[])",
      []
    );

    return result[0].toAddressArray();
  }

```

**Comment by schmidsi** [comment]
@ksvirsky Yes, casting changed: https://thegraph.com/docs/en/developer/assemblyscript-migration-guide/#casting

You can try:
```typescript
m.list = changetype<Bytes[]>(contract.getAddressList())
```

Worst case I'd try to loop through `contract.getAddressList()` and cast them one by one.

**Comment by ksvirsky** [comment]
@schmidsi  
`changetype` has resolved the error.
Thanks.
