### ISSUE TITLE
How to write event handler for  many-to-many relationships ?

### ISSUE THREAD

**Issue by gzliudan** [graphprotocol/graph-ts#263]
Given example in document:
```typescript
type Organization @entity {
  id: ID!
  name: String!
  members: [UserOrganization]! @derivedFrom(field: "organization")
}

type User @entity {
  id: ID!
  name: String!
  organizations: [UserOrganization!] @derivedFrom(field: "user")
}

type UserOrganization @entity {
  id: ID! # Set to `${user.id}-${organization.id}`
  user: User!
  organization: Organization!
}
```

How to set variable of Organization's members and User's organizations in event handler?

**Comment by incrypto32** [comment]
@gzliudan Can you give me some more context? What all event handlers are you using? In which handler are you setting the `organizations` field in `User` and `members` field of `Organization`.

Feel free to use The Graph [Discord](https://discord.gg/vtvv7FP) for quick resolution of such questions. It will be easier to assist over there.

**Comment by gzliudan** [comment]
for example: there are two Organizations named orgA and orgB, an event named NewUser is emited, the new user belongs to orgA and orgB, then how to set variable organizations of new users in handleNewUser event handler?

**Comment by evaporei** [comment]
As referred from the [docs](https://thegraph.com/docs/en/developer/create-subgraph-hosted/#many-to-many-relationships), it's just like a one-to-many relationship, but you have two entities related to the mapping table.

You can create an `User` and an `Organization` entities normally, and then link them through creating an `UserOrganization` entity with their IDs.

**Comment by azf20** [comment]
Thanks @evaporei ! @gzliudan closing this issue, please re-open if that didn't answer your question
