### ISSUE TITLE
How can I use ipfs.cat api?

### ISSUE THREAD

**Issue by ExtDev0327** [graphprotocol/graph-ts#276]
I tried to use ipfs.cat to fetch metadata from on-chain using hash value.
But this will be failed sometimes.
In this documentation[(https://thegraph.com/docs/en/developer/assemblyscript-api/#ipfs-api)], subgraph mentioned like as followed.

> Note: ipfs.cat is not deterministic at the moment. if the file cannot be retrieved over the IPFS network before the request times out, it will return null. Due to this, it's always worth checking the result for null. To ensure that files can be retrieved, they have to be pinned to the IPFS node that Graph Node connects to. On the hosted serviced, this is https://api.thegraph.com/ipfs/. See the IPFS pinning section for more information.

But I don't know how I can use the url ```https://api.thegraph.com/ipfs ```
I think developers who belongs to subgraph team can solve this problem.
Hope your kindly help.

**Comment by incrypto32** [comment]
@ExtDev0327 You can try pinning using this [ipfs-http-client](https://www.npmjs.com/package/ipfs-http-client) package. As  done by this user on the Graph Discord -> [Original Message](https://discord.com/channels/438038660412342282/438070183794573313/972444531016482816)


Feel free to reopen this issue if its not resolved

**Comment by nareshkatta99** [comment]
@incrypto32 
Always getting
`Forbidden
Only certain IPFS methods are allowed` 
error
when I try 
https://api.thegraph.com/ipfs/api/v0/pin?arg=QmUGVntd7DbxiWuGMZA5mL7Z2PmisDLw3dqDur6omqiSLd

**Comment by azf20** [comment]
hi @nareshkatta99 - it should no longer be required to pin the files to the Hosted service IPFS node, as it is able to find files via peering if your ipfs files are sufficiently available. The docs no longer recommend that accordingly

**Comment by darkeagle1236** [comment]
> hi @nareshkatta99 - it should no longer be required to pin the files to the Hosted service IPFS node, as it is able to find files via peering if your ipfs files are sufficiently available. The docs no longer recommend that accordingly

But i still got ipfs.cat timeout for new added files
