### ISSUE TITLE
Date.now not available in the subgraph

### ISSUE THREAD

**Issue by MathieuSimard** [graphprotocol/graph-ts#280]
I would like to have access to Date.now in a subgraph.

I have tried the following code.
```typescript
import { now } from 'assemblyscript/std/assembly/bindings/Date';
```
and
```typescript
export declare namespace Date {
    @external("env", "Date.now")
    export function now(): f64;
}
```
I was able to compile and deploy. However I get the following runtime error: 
```
unknown import: `Date.now` has not been defined 
```
and
```
unknown import: `env::Date.now` has not been defined 
```
Is it possible to have access to the current datetime in a subgraph?

**Comment by leoyvens** [comment]
Not possible as it would break determinism, what you can do is access the timestamp of the block which originated the trigger being handled.
