### ISSUE TITLE
Subgraph failed with non-deterministic error: Failed to transact block operations: subgraph writer poisoned by previous error, retry_delay_s: 1800, attempt: 369

### ISSUE THREAD

**Issue by TimDaub** [graphprotocol/graph-ts#287]
- I have a subgraph as a hosted service: https://thegraph.com/hosted-service/subgraph/timdaub/web3musicsubgraph?selected=logs
- But it stops indexing at block https://etherscan.io/block/14630345 and for months on end it has now thrown: `Subgraph failed with non-deterministic error: Failed to transact block operations: subgraph writer poisoned by previous error, retry_delay_s: 1800, attempt: 369`
- This is the commit tip: https://github.com/spinamp/web3-music-subgraph/commit/df22b3397ca4de4584216bde51f78ad8128e9873
- I've opened the issue at Spinamp too, but we don't know what's happening: https://github.com/spinamp/web3-music-subgraph/issues/17

**Comment by leoyvens** [comment]
This request will give you the root error

```
curl --location --request POST 'https://api.thegraph.com/index-node/graphql' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"{\n  indexingStatusForCurrentVersion(subgraphName: \"timdaub/web3musicsubgraph\") {\n    synced\n    health\n    entityCount\n    fatalError {\n      message\n      block {\n        number\n        hash\n      }\n      handler\n    }\n    chains {\n      chainHeadBlock {\n        number\n      }\n      latestBlock {\n        number\n      }\n    }\n  }\n}\n","variables":{}}'
```

which is
` invalid input value for enum sgd259740.music_platform: \"\"`

Not sure how this happens, maybe you tried to set an enum to an empty string or null?

**Comment by azf20** [comment]
I believe the default should maybe be `other` rather than `null`: https://github.com/spinamp/web3-music-subgraph/blob/cb25372e375f4e1e77ec15bff33a712bc2b61077/schema/shared.graphql#L29
The best place to get support on specific subgraph debugging is The Graph discord https://discord.gg/vtvv7FP
