### ISSUE TITLE
Convert Bytes32 to text

### ISSUE THREAD

**Issue by DeveloperInProgress** [graphprotocol/graph-ts#289]
Is there a conversion function equivalent to `parseBytes32String` from `ethers` : https://docs.ethers.io/v5/api/utils/strings/#utils-parseBytes32

**Comment by azf20** [comment]
hi! I think you can use one of the functions from [here](https://thegraph.com/docs/en/developer/assemblyscript-api/#bytes):
```
b.toHex() – returns a hexadecimal string representing the bytes in the array
b.toString() – converts the bytes in the array to a string of unicode characters
b.toBase58() – turns an Ethereum Bytes value to base58 encoding (used for IPFS hashes)
```
