### ISSUE TITLE
Setting Value of an Array

### ISSUE THREAD

**Issue by Data-Nexus** [graphprotocol/graph-ts#299]
I'm running into an issue with setting a value inside of my array:

Mapping
```
log.warning("_newSupplyOut = {}", [_newSupplyOut.toString()]);
 
_market.outputTokenSupply[_outputIndex] = _newSupplyOut;

log.warning("_market.outputTokenSupply: {}", [_market.outputTokenSupply[_outputIndex].toString()]);
```

Which returns in the logs:
```
_newSupplyOut = 100000000000000000, data_source: Silo
_market.outputTokenSupply: 0, data_source: Silo
```

In the database, I am seeing a 0 for the market.outputTokenSupply element as well.

**Comment by Data-Nexus** [comment]
Looks like I was able to get around this by modifying the element while the data is stored in a variable, then setting the variable back to the entity.

```
    let _newSupplyOut = _market.outputTokenSupply;

    _newSupplyOut[_outputIndex] = _market.outputTokenSupply[_outputIndex].plus(event.params.amount);

    log.warning("_newSupplyOut = {}", [_newSupplyOut[_outputIndex].toString()]);
    _market.outputTokenSupply = _newSupplyOut;

    log.warning("_market.outputTokenSupply = {}", [_market.outputTokenSupply[_outputIndex].toString()]);
```

**Comment by azf20** [comment]
hey @Data-Nexus - @evaporei can confirm but I think that is expected behaviour (I thought there was a note on this in the docs, but I am not easily finding it, so that might be a necessary addition)

**Comment by Data-Nexus** [comment]
If so, this can be closed :)
