### ISSUE TITLE
one address param always is null but actully it is a adress

### ISSUE THREAD

**Issue by shixin-guo** [graphprotocol/graph-ts#302]
owner is **null**
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/12186221/197730110-f156f36b-1c26-46e2-bdb0-8fca791d85c3.png">

but when I log it 
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/12186221/197730249-7ee0d828-052f-4969-bfd0-8b33ed1715ac.png">
it is fine

in my contract file I emit an event and include a param which is `address(this)`
<img width="303" alt="image" src="https://user-images.githubusercontent.com/12186221/197726178-56f5a439-55a4-4a7f-895f-34ecbb2da81a.png">

then I use the graph to collect this event and log this address,
<img width="700" alt="image" src="https://user-images.githubusercontent.com/12186221/197726647-823c8208-59ab-4e23-8862-78ad9896d743.png">

```
entity.owner = event.params.owner.toHexString()
log.info('create owner hash {}', [event.params.owner.toHexString()])
```

but the result I test the result in the graph studio editor, it is always null and other params always work fine, so I am confused about it these days

more info 

```
        - event: MarketItemCreated(indexed uint256,address,address,uint256,bool,string)
          handler: handleMarketItemCreated
```

abi 
```
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "seller",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "price",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "sold",
        "type": "bool"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "fileUrl",
        "type": "string"
      }
    ],
    "name": "MarketItemCreated",
    "type": "event"
  },
```

**Comment by azf20** [comment]
hey @shixin-guo can you share a link to a transaction emitting this event?

**Comment by shixin-guo** [comment]
thanks your replay, I got the root cause, I forget to assign the contract address(default owner) to a user entity,  

> From your query it seems `owner` field should specify a relation to an Owner/User entity. Are you sure you have an Owner/User entity with that address as an ID?
