### ISSUE TITLE
Indexed Structs getting converted to Bytes

### ISSUE THREAD

**Issue by fritzschoff** [graphprotocol/graph-ts#305]
If an address is indexed, it is fine. You can easily convert bytes to a string and save it in the entity. But if you are working with a struct that might even be in an array, it is nearly impossible to parse. 
Was encountering that issue when writing a unit test for a handler and it always throw an error 
```
Ethereum Value is not Bytes
```
On top of that it threw within an entity that doesn't have anything to do with the handle function. 
Once I removed the indexed paramter in the abi and in the signature, I got the correct typing and could parse it. 
So the question is, should we always convert indexed parameters to bytes?

**Comment by azf20** [comment]
hi @fritzschoff thanks! this is expected behaviour, see this comment https://github.com/graphprotocol/graph-node/issues/2707#issuecomment-900174543
