### ISSUE TITLE
Usage of BigInt failure

### ISSUE THREAD

**Issue by RyRy79261** [graphprotocol/graph-ts#309]
When accessing `import { BigInt } from '@graphprotocol/graph-ts'` this causes a compilation error in fastify
```
node_modules/@graphprotocol/graph-ts/index.ts:2
import './common/eager_offset'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by schmidsi** [comment]
This looks like it was imported into a TypeScript project while this repo is AssemblyScript. I'm aware that the naming is misleading and I created a task to rename it.
