### ISSUE TITLE
Bump AssemblyScript version

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-ts#37]
Our version is now a couple of months old, and in the meantime things like `super()` support have been added https://github.com/AssemblyScript/assemblyscript/pull/445. So it's a good time to bump again.

**Comment by sistemico** [comment]
I agree. Also, really useful helper functions (like convert numbers to strings https://github.com/AssemblyScript/assemblyscript/issues/369 https://github.com/AssemblyScript/assemblyscript/pull/373) have been added.
