### ISSUE TITLE
Rename toHex to make it more discoverable

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-ts#41]
Users keep using `bytes.toString()` to generate IDs for entities, which in most cases generates invalid UTF-8 and causes the subgraphs to fail.

Idea:
* Rename `toHex` to something more intuitive, like `toHexString`.
* Update the error message that people when using `toString()` to mention `toHexString()`
* Update documentation and example subgraphs.

**Comment by fordN** [comment]
When converting byte array for use as an ID or string field you need to use toHex() NOT toString() which is not obvious to many first time users.

Common use cases:
- Address type —> string
- keccak256() output —> string

How can we make it better?
- easier to get correct conversion fn on first try (often using type introspection)
- clarity between toHex() and toString()
- error message that facilitates efficient debugging

Updates

- Add more clearly named version of toHex() and update docs to include description
    - toString(value, 'hex') or toString(value, 'address') and split current to be toString(value, 'default')
    - toAddressString()
    - toHexString()
    - addressToString() - nice to include address in the name since often the source type will be address
    - asString()
- Make it very clear in the docs that setting up an IDE with type introspection is a "vital"
 part of the developer setup as I've noticed many developers skip that to get started faster and end up wasting time creating their mappings.
- Better error message with table of eth type → schema type and which conversion should be used? see below

Conversion Reference Table

| Source   |      Destination      |  Conversion |
|----------|:-------------:|------|
| Address |  String | toHexString() |
| Address | ID | toHexString() |
| Keccak256() | String | toHexString() |
| Address | Bytes | none |
| Bytes | Bytes | none |
| boolean | boolean | none |
| ... | ... | ... |

**Comment by fordN** [comment]
To Do: 
- [ ] Decide on a more intuitive function name
- [ ] Add new ByteArray.toHex() implementation with the more intuitive name
- [ ] Update the error message output for toString() errors to mention toHex() (or new name)
- [ ] ?Include conversion reference table or subset of it in the error message output?
- [ ] Update example subgraphs and documentation to reflect new fn name

**Comment by Jannis** [comment]
I'm leaning towards just adding `toHexString()` and updating the UTF-8 error message in graph-node to say something along the lines of `This may be caused by converting a value such as an address or a byte array to a string with 'toString()'. Try 'toHexString()' instead.`

The conversion table is great, I think we should add it to the docs instead though.
