### ISSUE TITLE
Missing bytes helpers

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-ts#47]
Helpers that have been requested by Gnosis:

- Unsigned `Bytes` to `BigInt` conversion
- i32 to `Bytes` conversion (and the other way around)
- String to `Bytes` conversion

**Comment by leodasvacas** [comment]
We'll need little endian and big endian versions for Bytes conversion, see how Gnosis handled it [here](https://github.com/gnosis/hg-subgraph/blob/d9fbce1354dc9dc08e9cf0d2305f66c14e8f5c73/src/mapping.ts#L131).

**Comment by leodasvacas** [comment]
Tasks and summarized plans:

- [ ] (1d) Testing framework that compiles AS unit tests to WASM and runs them, so that we can have confidence in the helpers written entirely in AS.

- [ ] (0.5d) Unsigned Bytes to BigInt conversion, this involves the following methods on `BigInt`:
  - `fromSignedBytes(bytes: Bytes): BigInt`
  - `fromUnsignedBytes(bytes: Bytes): BigInt`

The `Bytes` are assumed to be little-endian since WASM is little-endian. That assumption may be false if the bytes come from an external system, so we add a `reverse()` method to reverse the Bytes in place, which is useful to convert endianess.

- [ ] (0.5d) i32 to Bytes conversion, and the other way around. Adding to `Bytes`:
  - `fromI32(x: i32)`: Bytes
     - Returns bytes in little-endian order.
  - `toI32(): i32`
     - Assumes the bytes are in little-endian order.

- [ ] (0.5d) String to Bytes conversion. Adds to `Bytes`:
  - `fromString(s: String): Bytes`
     - Copies the string to an UTF8 byte array.

**Comment by fubhy** [comment]
I just had the need for a hex to ascii converter. In case that comes up again:

```
function hexToAscii(hex: string): string {
  let output = '';
  for (let i = 0; i < hex.length; i += 2) {
    let slice = parseInt(hex.substr(i, 2), 16) as i32;

    if (slice) {
      output += String.fromCharCode(slice);
    }
  }

  return output;
}
```

**Comment by leodasvacas** [comment]
@fubhy Thanks for sharing that, it's a great reference on how to implement those conversions. I actually hadn't considered that use case, we should also add `fromHexString(s: String): Bytes` so you could then achieve that by doing `Bytes.fromHexString(hex).toString()`.

**Comment by PaulRBerg** [comment]
For anyone stumbling upon this issue, note that the bytes helpers have been added in #57.

I left this comment because it's not immediately obvious whether this issue has been fixed or just closed.
