### ISSUE TITLE
Logging module for mappings

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-ts#5]

**Comment by leodasvacas** [comment]
It would be easy to log through Rust but then the question is how to get those logs to the user. An idea is to have a `Log` entity in graphql schemas to which users could subscribe.

**Comment by leodasvacas** [comment]
daostack defined a `Log` entity in the schema to get logs through GraphQL, an interesting take on this, it's pattern that can be used for people that want custom structured logging.

**Comment by Jannis** [comment]
# Requirements

* Mappings are able to log to the graph-node standard output and the per-subgraph Elasticsearch logs.
* It is convenient to log `BigInt`, `BigDecimal`, `Address`, `Bytes`, `EthereumEvent`, `EthereumCall` (and _maybe_ `EthereumTransaction`, `EthereumBlock`) values as well as built-in AssemblyScript types (`i32` etc.).
* Different logging levels are supported. 
* Panicking or throwing is possible, terminates the subgraph and generates logs.

# Research

* Template strings are not supported yet.
* What's the current state of converting values to strings in AssemblyScript?
* How could we implement format strings?
