### ISSUE TITLE
Error when importing BigInt into AssemblyScript project

### ISSUE THREAD

**Issue by OR13** [graphprotocol/graph-ts#55]
I'm interested in just using the BigInt AssemblyScript Library. I started with a new AssemblyScript project, and attempted to import the library and immediately encountered compilation errors. I looked at examples, but all are far more complicated that what I want to do. I just want to use BigInt in AssemblyScript.

https://github.com/OR13/pusheen/blob/master/assembly/index.ts

```

ERROR TS2300: Duplicate identifier '__memory_allocate'.

 @global export function __memory_allocate(size: usize): usize {
                         ~~~~~~~~~~~~~~~~~
 in ~lib/@graphprotocol/graph-ts(17,24)

ERROR TS2300: Duplicate identifier '__memory_free'.

 @global export function __memory_free(ptr: usize): void { /* nop */ }
                         ~~~~~~~~~~~~~
 in ~lib/@graphprotocol/graph-ts(35,24)

ERROR TS2300: Duplicate identifier '__memory_reset'.

 @global export function __memory_reset(): void {
                         ~~~~~~~~~~~~~~
 in ~lib/@graphprotocol/graph-ts(37,24)

ERROR TS2305: Module '~lib/@graphprotocol/graph-ts' has no exported member 'BigInt'.

 import { BigInt } from "@graphprotocol/graph-ts";
          ~~~~~~
 in assembly/index.ts(4,9)
```

I'm probably doing something obviously wrong here, I don't have much experience with AssemblyScript.

**Comment by Jannis** [comment]
You could drop your `import 'allocator/arena'` but it's worth noting that graph-ts is not a standalone library. It requires the host to export functions that implement most of the BigInt and other APIs.

**Comment by OR13** [comment]
@Jannis thanks, I figured that was the case peeking at it in node_modules. I'm interested in building a cryptographic accumulator on top of `graph-ts` data types. I don't want to use IPFS or Ethereum, just assemblyscript -> wasm. Does this sound like a totally impractical use of the lib?

**Comment by Jannis** [comment]
@OR13 At the moment, yes, because whatever you run the wasm module in would have to provide host exports for `BigInt`, `BigDecimal` or whatever you intend to use:
https://github.com/graphprotocol/graph-ts/blob/f5ceb9cb743f8fa5137858ac46d79f50029f9806/index.ts#L46-L79

**Comment by Jannis** [comment]
Now, if someone implemented our `BigInt` class purely in AssemblyScript, thing would look different.

**Comment by OR13** [comment]
@Jannis haha, thats what I'm trying to avoid... This is the closest project afaik: https://github.com/MaxGraey/bignum.wasm

Thanks for your comments. I'm gonna close this issue.
