### ISSUE TITLE
Impossible to get from a `Uint8Array` back to a `ByteArray`

### ISSUE THREAD

**Issue by Arachnid** [graphprotocol/graph-ts#64]
If I call, for instance, `subarray` on a `ByteArray` object, the returned type is `Uint8Array`. This lacks the extra methods such as `.toHexString()` that `ByteArray` exposes, and there doesn't appear to be any documented way to construct a `ByteArray` from a `Uint8Array`.

**Comment by leoyvens** [comment]
A `ByteArray` is a subclass of `Uint8Array` with no extra fields, you can just `x as ByteArray`.

**Comment by Arachnid** [comment]
Can you? What it's not a `ByteArray` internally, but an instance of the parent class, or some other subclass?

**Comment by leoyvens** [comment]
I believe it should always work.
