### ISSUE TITLE
Improve failure message when attempting to access unset field

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-ts#79]
The error right now says something like `Value is not i32`, which is not very helpful.

**Comment by leoyvens** [comment]
Investigating the bad error message people get when non-nullable fields are accessed without being set, the first thing I managed to was get a `MemoryAccessOutOfBounds`, didn't even know that could happen. My conclusion is that graph-ts or graph-cli are not at fault here, the error messages are bad because the situation is assumed to never happen, and that assumption should be reliable if graph-node wasn't returning bad data.

So IMO this should be fixed in graph-node, we should forbid `store.set` from setting entities with missing non-nullable fields. This is a breaking change, but we're already _almost_ doing this for relational schemas except we're only checking when applying the changes to the DB, so I think we should bundle this check along with the relational schema changes.

**Comment by Jannis** [comment]
I agree, we should check for non-nullable fields in `store.set`.

It looks to me like `Value is not an i32` is not logged when a value is `null` but rather when it is of the wrong kind. How can that happen (unless you deliberately mis-cast in the mappings or bypass codegen altogether)?

**Comment by leoyvens** [comment]
@Jannis That happens when the value goes unset, or is set to null, across blocks. Which will already be fixed by the relational schema.

**Comment by leoyvens** [comment]
I'll consider this closed by #1268 unless someone can reproduce an error like this on master, with relation schemas on.
