### ISSUE TITLE
IPFS fetching files in folder 

### ISSUE THREAD

**Issue by wighawag** [graphprotocol/graph-ts#84]
According to the documentation ipfs.cat expect a hash (see https://thegraph.com/docs/assemblyscript-api)

Unfortunately sometime the ipfs file registered in a contract is actually inside a folder
It would be great if the ipfs.cat command could accept something like 'QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/0.json'

**Comment by Jannis** [comment]
Hi! That should be easy enough to do. I suspect that any limitation here is artificial.

**Comment by Jannis** [comment]
@wighawag I just tried this using the following:

1. I started a local graph-node
2. I created a fresh subgraph with `graph init --from-example jannis/gravity`
3. I added a `data: String` field to `Gravatar`
4. I added the following to the `handleNewGravatar` handler:
    ```typescript
    let data = ipfs.cat('QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/Makefile')
    gravatar.data = data.toString()
    gravatar.save()
    ```
5. Then I deployed this subgraph locally.
6. After it had indexed a few events, I ran a query that included the new `data` field:
    ![image](https://user-images.githubusercontent.com/19324/67685110-c3628300-f994-11e9-9341-3c8042e9c2a7.png)

As you can see this already works. We will add a note to our docs to say that IPFS paths like this are also supported.

Note: The file you mentioned (`QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/0.json`) does not exist in that folder. Perhaps that was the problem?
