### ISSUE TITLE
Unrecoverable error when calling contract that return 0x

### ISSUE THREAD

**Issue by wighawag** [graphprotocol/graph-ts#85]
I got the following error when deploy my graph :
```
Subgraph instance failed to run: Failed to process trigger: Failed to handle Ethereum event with handler "handleTransfer": Failed to call function "supportsInterface" of contract "EIP721": ABI error: please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don't exist, code: SubgraphSyncingFailure, id: QmPhZ4f4ZJoim2kqaFLgBoHgmWByQYLaE9RxDrVWBMtMrm
```

What I think is happening is that the contract `0x55b9a11c2e8351b4ffc7b11561148bfac9977855` is returning some data, maybe 0x that graph-ts is interpreting as an error but there seems to be no way to react on it. the whole graph shut down.

When I call it through ethers.js is says it revert. So maybe the error is in the internal call and that is why it does not even reach where I check for `result.reverted`

What I want to do is simply check if the contract supports an interface.
If it revert, I consider that it does not. if it does return I check if the value is `true`

Unfortunately doing the following is not sufficient:

```
function supportsInterface(contract: EIP721, interfaceId: String, expected : boolean = true) : boolean {
  let supports = contract.try_supportsInterface(toBytes(interfaceId));
  return !supports.reverted && supports.value == expected;
}
```
So I do that but it is still not enough
```
function supportsInterface(contract: EIP721, interfaceId: String, expected : boolean = true) : boolean {
    let result = contract.tryCall('supportsInterface', [EthereumValue.fromFixedBytes(toBytes(interfaceId))]);
    if (result.reverted) {
        return false;
    }
    let value = result.value;
    if(value.length == 0) {
        return !expected;
    }
    let firstValue = value[0];
    let byteValue = changetype<Bytes>(value[0].data as u32);
    if(byteValue.length == 0) {
        return !expected;
    }
    return firstValue.toBoolean() == expected;
}
```

It would be great if there was a way to allow us to react on wrong data

**Comment by Jannis** [comment]
@leoyvens What do you think?

**Comment by wighawag** [comment]
I can confirm the result of the node is "0x" and graph-ts does not handle it

This is the request you can send to your node :
```
{
	"jsonrpc":"2.0",
	"id":1, 
	"method":"eth_call",
	"params":[
		{
			"to": "0x55b9a11c2e8351b4ffc7b11561148bfac9977855",
			"data": "0x01ffc9a701ffc9a700000000000000000000000000000000000000000000000000000000"
		},
		"latest"
	]
}
```

and it will return 
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x"
}
```

**Comment by wighawag** [comment]
This is the same as this issue : https://github.com/graphprotocol/support/issues/33

**Comment by leoyvens** [comment]
@wighawag It really is the same, well observed! We have to be careful to detect if Geth is being used when checking for this, otherwise using Geth can cause non-determinism because it returns `0x` for timeouts, but it should be doable.

**Comment by wighawag** [comment]
ok, interesting, geth used to also return 0x when requesting data for a block (via blockNumber param) not yet synced. See https://github.com/ethereum/go-ethereum/issues/15102

And here again this is a bug in geth. Geth should error out explicitly. Have you already submitted a bug on geth for that ?

**Comment by leoyvens** [comment]
@wighawag It would be awesome if Geth changed this, there's already this bug #19027 about reverts being ambiguous but it has gotten no attention.

**Comment by leoyvens** [comment]
Actually it looks like they did fix the timeout error, https://github.com/ethereum/go-ethereum/pull/19737, which means we may be able to get away with assuming `0x` is a deterministic error.

**Comment by colonelssecretspices** [comment]
Hi I am encounter this error with `0x` being "indeterminate" is there any work around for this, or is this determinate in a newer version?
