### ISSUE TITLE
when using log, no event get processed when running against a local graph-node

### ISSUE THREAD

**Issue by wighawag** [graphprotocol/graph-ts#88]
I have a weird issue.

I use log to trace info and it works well when I deploy it to thegraph.com

But when I try with a local docker instance of graph-node no event get processed and as a result there is no entities stored

If I comment out every call to log, the issue disapear.

**Comment by Jannis** [comment]
@wighawag Could you post your mapping code before and after commenting things out?

Also, just in case: is the subgraph available for us to test locally?

**Comment by wighawag** [comment]
the sub-graph latest is in that branch:  https://github.com/wighawag/eip721-subgraph/tree/contract_entity

You can see there the mapping code. If you comment out the log call, the local-graph get populated with the entities, if not, nothing get recorded

**Comment by Jannis** [comment]
@wighawag There's a problem with the log parameters. The following lines use two `{}` placeholders in the format string but only pass one argument in:

* https://github.com/wighawag/eip721-subgraph/blob/contract_entity/src/mapping.ts#L58
* https://github.com/wighawag/eip721-subgraph/blob/contract_entity/src/mapping.ts#L60
* https://github.com/wighawag/eip721-subgraph/blob/contract_entity/src/mapping.ts#L62
* https://github.com/wighawag/eip721-subgraph/blob/contract_entity/src/mapping.ts#L70

That should work neither on the hosted service nor locally. It should cause your subgraphs to fail actually.

**Comment by wighawag** [comment]
Oups, my bad, sorry, I changed that recently, might have never deployed that version actually.

What's the best way to catch these issues when running locally, is that in the docker log ? Seems these do not show up by default. Any doc on that ?

**Comment by Jannis** [comment]
When your subgraph fails, the graph-node docker logs will include the error and log messages stating the the subgraph is terminated.

**Comment by wighawag** [comment]
Ha, I see, did not notice it among all the log output and I think while I deployed such version online, it never reached to the log due to https://github.com/graphprotocol/graph-ts/issues/85
